name: Update Kakao & Naver Ranking

on:
  schedule:
    # 매일 한국 시간 오후 8시 실행 (UTC 11:00)
    - cron: '0 11 * * *'
  workflow_dispatch: # 수동 실행 버튼
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright beautifulsoup4
          playwright install chromium

      - name: Run main.py (Kakao + Naver)
        env:
          # GitHub Secrets에 저장한 구글 웹앱 주소
          WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
        run: python main.py

              - name: Push JSON to Lovable_Dashboard
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${GH_TOKEN}@github.com/wo0h881-dev/Lovable_Dashboard.git

          mkdir -p Lovable_Dashboard/public/data

          cp public/data/kakao-promotions-today.json Lovable_Dashboard/public/data/
          cp public/data/naver-promotions-today.json Lovable_Dashboard/public/data/
          cp public/data/ridi-promotions-today.json Lovable_Dashboard/public/data/

          cd Lovable_Dashboard

          git add public/data/kakao-promotions-today.json
          git add public/data/naver-promotions-today.json
          git add public/data/ridi-promotions-today.json

          git commit -m "update promotion json" || echo "No changes"

          git push
